
name: stats

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        id: script
        with:
          fail-on-error: false
          script: |
            import glob, os, sys

            included_files = "cs,uml,txt,ltx,tex,md,yml,csproj,nuspec,gitignore,py".split(",")
            base_path = os.getcwd()
            paths = [
              "",
              ".github/workflows",
              "src/MaTeX",
              "src/MaTeX/TestFiles"
            ]

            all_files = []
            for path in paths:
              for file in os.listdir(os.path.abspath(os.path.join(base_path, path))):
                if file.lower().split(".")[-1] in included_files:
                  all_files.append(os.path.abspath(os.path.join(base_path, path, file)))

            lines, chars = 0, 0
            for file in all_files:
              chars += os.path.getsize(file)
              print(file)
              try:
                with open(file, "r") as fobj:
                  lines += len(fobj.readlines())
              except:
                print("error")

            print("\n" + lines)

      - name: Save result
        run: printenv "SCRIPT_STDOUT"
        env:
          SCRIPT_STDOUT: ${{ steps.script.outputs.stdout }}
